In [33]:
# Importing Image class from PIL module
from PIL import Image,ImageFilter
 
# Opens a image in RGB mode
im = Image.open(r"12.png").convert('RGB')
 
# Blurring the image
#im1 = im.filter(ImageFilter.BoxBlur(14)) # 4 to 14
#im2 = im.filter(ImageFilter.GaussianBlur(5)) # 2 to 6

im = im.resize((50,50))

import random
#im3 = im.filter(ImageFilter.BoxBlur(random.randint(2, 7))).filter(
#           ImageFilter.GaussianBlur(random.randint(1, 3)))

#im3 = im.filter(ImageFilter.BoxBlur(random.randint(1, 5)))

#im3 = im.filter(ImageFilter.GaussianBlur(random.randint(1, 3)))

im3 = im.filter(ImageFilter.BoxBlur(random.randint(1, 2))).filter(
           ImageFilter.GaussianBlur(random.randint(1, 1)))



#im1.save("a2.jpeg")
#im2.save("a3.jpeg")
im3.save("a12.png")

In [42]:
import numpy as np
x = np.array(im3,np.float32)

In [43]:
x = np.moveaxis(x, -1, 0)

In [44]:
x.shape

(3, 50, 50)

In [45]:
x[0].shape

(50, 50)

In [47]:


n.shape

(50, 150)

In [25]:
import numpy as np
x = np.array([[[155,  33, 129],
        [161, 218,   6]],

       [[215, 142, 235],
        [143, 249, 164]],

       [[221,  71, 229],
        [ 56,  91, 120]],

       [[236,   4, 177],
        [171, 105,  40]]])

In [31]:
m = np.hstack((x[0],x[1]))
n = np.hstack((m,x[2]))
n

array([[155,  33, 129, 215, 142, 235, 221,  71, 229],
       [161, 218,   6, 143, 249, 164,  56,  91, 120]])

In [29]:
.

array([[155,  33, 129],
       [161, 218,   6]])

In [26]:
x

array([[[155,  33, 129],
        [161, 218,   6]],

       [[215, 142, 235],
        [143, 249, 164]],

       [[221,  71, 229],
        [ 56,  91, 120]],

       [[236,   4, 177],
        [171, 105,  40]]])

In [21]:
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg19 import preprocess_input
import numpy as np

model = VGG19(weights='imagenet', include_top=False)

img_path = '/home/gamal/Datasets/Dataset1/Faces/ufuRTqz29no_278.866667_283.900000_face_3.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)


1/1 [==============================] - 0s 82ms/step


In [12]:
features.max()

154.96358

In [32]:
features.min()

0.0

In [22]:
features.squeeze().shape

(512,)

In [13]:
random.randint(1, 3)

1

In [5]:
features.shape

(1, 7, 7, 512)

In [9]:
new_arr = features.reshape(-1, features.shape[-1])

In [10]:
new_arr.shape

(49, 512)

In [4]:
import numpy as np
z1 = np.zeros((190,128))

In [33]:
z = np.array( [[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [39]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
z.shape

(4, 3)

In [41]:
z.reshape(2,-1).squeeze()

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [42]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
z[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
image = Image.open("12.png").convert('RGB')
im = image.resize((49,49))

im3 = im.filter(ImageFilter.BoxBlur(random.randint(1, 2))).filter(
    ImageFilter.GaussianBlur(random.randint(1, 1)))

pix = np.array(im3,np.float32)
pix = pix / 255
pix = np.moveaxis(pix, -1, 0)
print(pix.shape)

m = np.hstack((pix[0],pix[1]))
n = np.hstack((m,pix[2]))
print(n.shape)

z1 = np.ones((49,768-(3*49)))
print(z1.shape)
image_guide = np.hstack((n,z1))
print(image_guide.shape)

image.close()
im.close()
im3.close()

(3, 49, 49)
(49, 147)
(49, 621)
(49, 768)
