In [3]:
# Importing Image class from PIL module
from PIL import Image,ImageFilter
 
# Opens a image in RGB mode
im = Image.open(r"a1.jpeg")
 
# Blurring the image
#im1 = im.filter(ImageFilter.BoxBlur(14)) # 4 to 14
#im2 = im.filter(ImageFilter.GaussianBlur(5)) # 2 to 6

import random
im3 = im.filter(ImageFilter.BoxBlur(random.randint(2, 7))).filter(
            ImageFilter.GaussianBlur(random.randint(1, 3)))

#im1.save("a2.jpeg")
#im2.save("a3.jpeg")
im3.save("a4.jpeg")

In [21]:
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg19 import preprocess_input
import numpy as np

model = VGG19(weights='imagenet', include_top=False)

img_path = '/home/gamal/Datasets/Dataset1/Faces/ufuRTqz29no_278.866667_283.900000_face_3.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)


1/1 [==============================] - 0s 82ms/step


In [12]:
features.max()

154.96358

In [32]:
features.min()

0.0

In [22]:
features.squeeze().shape

(512,)

In [13]:
random.randint(1, 3)

1

In [5]:
features.shape

(1, 7, 7, 512)

In [9]:
new_arr = features.reshape(-1, features.shape[-1])

In [10]:
new_arr.shape

(49, 512)

In [4]:
import numpy as np
z1 = np.zeros((190,128))

In [33]:
z = np.array( [[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [39]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
z.shape

(4, 3)

In [41]:
z.reshape(2,-1).squeeze()

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [42]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
z[0:2]

array([[1, 2, 3],
       [4, 5, 6]])